//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rieltorAgensy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notifications
    {
        public int NotificationsID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> DealID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Text { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Deals Deals { get; set; }
    }
}
