//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rieltorAgensy
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyHistory
    {
        public int HistoryID { get; set; }
        public Nullable<int> PropertyID { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public string FieldName { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
    
        public virtual Propertiezzz Propertiezzz { get; set; }
    }
}
