//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rieltorAgensy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Propertiezzz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Propertiezzz()
        {
            this.Deals = new HashSet<Deals>();
            this.PropertyFeatures = new HashSet<PropertyFeatures>();
            this.PropertyHistory = new HashSet<PropertyHistory>();
            this.PropertyImages = new HashSet<PropertyImages>();
        }
    
        public int PropertyID { get; set; }
        public string Address { get; set; }
        public string PropertyType { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Size { get; set; }
        public Nullable<int> Bedrooms { get; set; }
        public Nullable<int> Bathrooms { get; set; }
        public string Description { get; set; }
        public Nullable<int> PropertyStatusID { get; set; }
        public Nullable<int> PropertyTypeID { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deals> Deals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyFeatures> PropertyFeatures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyHistory> PropertyHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyImages> PropertyImages { get; set; }
        public virtual PropertyStatuses PropertyStatuses { get; set; }
        public virtual PropertyTypes PropertyTypes { get; set; }
    }
}
