//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rieltorAgensy
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyImages
    {
        public int ImageID { get; set; }
        public Nullable<int> PropertyID { get; set; }
        public string ImagePath { get; set; }
    
        public virtual Propertiezzz Propertiezzz { get; set; }
    }
}
